apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: argoresource
type: Opaque
data:
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: d29yZHByZXNz  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: argoresource
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: argoresource
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: argoresource
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: longhorn
